//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CPUBench2004.rc
//
#define IDC_UPDATE                      3
#define IDC_BENCHDETAILS                3
#define IDC_GRAPHOFRESULT               6
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CPUBENCH2004_DIALOG         102
#define IDD_BENCHMARKSETTINGSDLG_DIALOG 103
#define IDD_CPUINFOITEMDLG_DIALOG       104
#define IDD_OSINFOITEMDLG_DIALOG        105
#define IDD_SYSINFODLG_DIALOG           106
#define IDD_EXTCPUINFOITEMDLG_DIALOG    107
#define IDD_EXTOSINFODLG_DIALOG         108
#define IDD_EXTMEMORYINFODLG_DIALOG     109
#define IDD_EXTMBINFODLG_DIALOG         110
#define IDD_CACHEINFODLG_DIALOG         111
#define IDD_CPUFEATURESDLG_DIALOG       112
#define IDD_DEVICESLISTDLG_DIALOG       113
#define IDD_REPORTDLG_DIALOG            114
#define IDD_RESULTDLG_DIALOG            115
#define IDD_SPLASHDLG_DIALOG            116
#define IDR_MAINFRAME                   128
#define IDC_RUNBENCHMARK                1000
#define IDC_BUTTON2                     1001
#define IDC_EXIT                        1002
#define IDC_TITLE1                      1004
#define IDC_TITLE2                      1005
#define IDC_CONFIGURE                   1006
#define IDC_WINDOWSMEDIA                1008
#define IDC_DIRECT3D                    1009
#define IDC_TITLE3                      1010
#define IDC_CAD                         1011
#define IDC_DB                          1012
#define IDC_TITLE4                      1013
#define IDC_RT1                         1014
#define IDC_RAM                         1016
#define IDC_ADVINFO                     1017
#define IDC_RAM2                        1017
#define IDC_CACHEINFO                   1018
#define IDC_RAM3                        1018
#define IDC_CPUNAME                     1019
#define IDC_RT2                         1019
#define IDC_CPUVENDOR                   1020
#define IDC_BRANDNAME                   1021
#define IDC_SIGNATURE                   1022
#define IDC_BUSTYPE                     1023
#define IDC_SOCKETNAME                  1024
#define IDC_CODENAME                    1025
#define IDC_FREQUENCY                   1026
#define IDC_PLATFORM                    1026
#define IDC_L1INSTRCACHE                1027
#define IDC_L1DATACACHE                 1028
#define IDC_L2CACHE                     1029
#define IDC_BUSSPEED                    1030
#define IDC_TRACECACHE                  1031
#define IDC_MEMFREE                     1031
#define IDC_MORE                        1032
#define IDC_OSNAME                      1033
#define IDC_CPULOGO                     1034
#define IDC_REVISION                    1034
#define IDC_LBL1                        1035
#define IDC_USERNAME                    1035
#define IDC_VENDORNAME                  1036
#define IDC_COMPUTERNAME                1036
#define IDC_LBL4                        1037
#define IDC_SERVICEPACK                 1037
#define IDC_LBL2                        1038
#define IDC_STANDBY                     1038
#define IDC_LBL5                        1039
#define IDC_LBL3                        1040
#define IDC_MAINDIRECTORY               1040
#define IDC_FEATURES                    1041
#define IDC_CACHEDETAILS                1042
#define IDC_BOOTMODE                    1042
#define IDC_TOTALLOAD                   1043
#define IDC_RESOLUTION                  1043
#define IDC_PAGEFILEFREE                1044
#define IDC_RAMFREE                     1045
#define IDC_USERFREE                    1046
#define IDC_CPUFREQUENCY                1048
#define IDC_FREQUENCYRANGE              1049
#define IDC_FREQUENCYRATIO              1050
#define IDC_L1ICACHE                    1051
#define IDC_L1DCACHE                    1052
#define IDC_DEFVCORE                    1053
#define IDC_HTSUPPORT                   1054
#define IDC_MMX                         1055
#define IDC_SSE                         1056
#define IDC_SSE2                        1057
#define IDC_SSE3                        1058
#define IDC_PSE36                       1061
#define IDC_AMD64                       1063
#define IDC_MEMLOAD                     1064
#define IDC_PAGEFREE                    1065
#define IDC_RAMFREEPERCENT              1066
#define IDC_USERFREEPERCENT             1067
#define IDC_PHYSMEM                     1068
#define IDC_PAGESIZE                    1069
#define IDC_VIRTUALSIZE                 1070
#define IDC_MEMFREEVAL                  1071
#define IDC_OTHERPCI                    1072
#define IDC_BIOSNAME                    1073
#define IDC_BIOSVERSION                 1074
#define IDC_BIOSDATE                    1075
#define IDC_CHIPSETID                   1076
#define IDC_CHIPSETVENDOR               1077
#define IDC_NAME                        1079
#define IDC_LBL                         1080
#define IDC_FSBSPEED                    1081
#define IDC_LBL9                        1081
#define IDC_PCILATENCY                  1082
#define IDC_LBL10                       1082
#define IDC_LBL6                        1083
#define IDC_LBL11                       1083
#define IDC_LBL7                        1084
#define IDC_LBL8                        1085
#define IDC_LBL13                       1085
#define IDC_CACHELATENCY                1086
#define IDC_TESTERNAME                  1086
#define IDC_MAINTITLE                   1087
#define IDC_LBL15                       1087
#define IDC_SYSTEMNAME                  1087
#define IDC_CREATEREPORT                1088
#define IDC_LBL17                       1089
#define IDC_LBL18                       1090
#define IDC_MBINFO                      1090
#define IDC_DEVLIST                     1090
#define IDC_PCIDEVS                     1091
#define IDC_TITLE                       1091
#define IDC_LOGO                        1092
#define IDC_L1DTLB4M_ASS                1094
#define IDC_L1ITLB4M_ASS                1095
#define IDC_SYSTEMDETAILS               1095
#define IDC_L1DTLB4M_ENTRIES            1096
#define IDC_INCLUDETESTERINFO           1096
#define IDC_L1ITLB4M_ENTRIES            1097
#define IDC_BENCHRESULTS                1097
#define IDC_L1D_TLB4K_ASSOCIATIVITY     1098
#define IDC_CPUFEATURES                 1098
#define IDC_L1I_TLB4K_ASSOCIATIVITY     1099
#define IDC_L1D_TLB4K_ENTRIES           1100
#define IDC_L1I_TLB4K_ENTRIES           1101
#define IDC_L1D_ASSOCIATIVITY           1102
#define IDC_L1D_LINESIZE                1103
#define IDC_L1D_LINESPERTAG             1104
#define IDC_L1D_CACHESIZE               1105
#define IDC_L1I_ASSOCIATIVITY           1107
#define IDC_L1I_LINESIZE                1108
#define IDC_L1I_LINESPERTAG             1109
#define IDC_L1I_CACHESIZE               1111
#define IDC_L2D_TLB4M_ASSOCIATIVITY     1112
#define IDC_L2I_TLB4M_ASSOCIATIVITY     1113
#define IDC_L2D_TLB4M_ENTRIES           1114
#define IDC_L2I_TLB4M_ENTRIES           1115
#define IDC_L2D_TLB4K_ASSOCIATIVITY     1116
#define IDC_L2I_TLB4K_ASSOCIATIVITY     1117
#define IDC_L2D_TLB4K_ENTRIES           1118
#define IDC_L2I_TLB4K_ENTRIES           1119
#define IDC_L2_ASSOCIATIVITY            1120
#define IDC_L2_LINESIZE                 1121
#define IDC_L2_LINESPERTAG              1122
#define IDC_L2_CACHESIZE                1124
#define IDC_L2CACHE_ASSOCIATIVITY2      1125
#define IDC_L2CACHE_LINESIZE2           1126
#define IDC_L2CACHE_LINESPERTAG2        1127
#define IDC_L1_DATA_CACHE_SIZE4         1128
#define IDC_L2CACHE_SIZE2               1129
#define IDC_RESULT                      1174
#define IDC_RESULT2                     1175
#define IDC_LBLTOTAL                    1176
#define IDC_LBLRAMSCORE                 1177
#define IDC_TIME                        1190
#define IDC_RAMSCORE                    1191
#define IDC_CPUINFO                     1252
#define IDC_OSINFO                      1253
#define IDC_BANNER                      1312
#define IDC_BANNER2                     1313
#define IDC_BANNER3                     1314
#define IDC_RESULTCTRL                  1323
#define IDC_SAVE_PROJECT                32808

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        189
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
